version: "3"

services:
  valheim:
    image: lloesche/valheim-server
    cap_add:
    - sys_nice
    volumes:
    - ./config:/config
    - ./data:/opt/valheim
    - $HOST_BACKUPS_DIRECTORY:/valheim-backups
    ports:
    - "2456-2457:2456-2457/udp"
    - "9001:9001/tcp"
    - "8080:80/tcp"
    environment:
    - SERVER_PUBLIC=$SERVER_PUBLIC
    - SERVER_NAME=$SERVER_NAME
    - SERVER_PASS=$SERVER_PASS
    - WORLD_NAME=$WORLD_NAME
    - SUPERVISOR_HTTP=$SUPERVISOR_HTTP
    - SUPERVISOR_HTTP_USER=$SUPERVISOR_HTTP_USER
    - SUPERVISOR_HTTP_PASS=$SUPERVISOR_HTTP_PASS
    - STATUS_HTTP=$STATUS_HTTP
    - BACKUPS_DIRECTORY=/valheim-backups
    - VALHEIM_PLUS=$VALHEIM_PLUS
    restart: always
    stop_grace_period: 2m
